In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="1"

In [19]:
!python TripletMarginLossLivedoor.py

torch.Size([128, 512])
tensor([[    2,  1433,  7978,  ...,  8333, 12175,     3],
        [    2, 15173, 17734,  ...,     0,     0,     0],
        [    2,    63, 15701,  ...,    19,    48,     3],
        ...,
        [    2,  7786,    14,  ...,   139,   120,     3],
        [    2, 17057,   159,  ...,  7341,    14,     3],
        [    2, 13901,  1993,  ..., 13298,   415,     3]])
torch.Size([128])
tensor([6, 1, 4, 4, 5, 1, 4, 2, 1, 8, 0, 4, 1, 4, 3, 6, 1, 2, 8, 7, 7, 5, 6, 8,
        7, 8, 0, 1, 8, 6, 4, 3, 1, 0, 5, 7, 1, 2, 6, 5, 4, 8, 8, 0, 5, 0, 6, 1,
        2, 6, 3, 8, 5, 2, 3, 7, 4, 7, 2, 4, 4, 8, 7, 7, 0, 3, 0, 5, 7, 1, 1, 4,
        5, 7, 5, 5, 1, 0, 8, 2, 2, 8, 5, 7, 2, 2, 2, 8, 1, 1, 7, 8, 4, 3, 4, 2,
        2, 5, 1, 1, 6, 8, 3, 5, 1, 8, 6, 4, 5, 0, 2, 0, 7, 3, 6, 5, 6, 7, 3, 2,
        6, 3, 7, 0, 4, 0, 4, 1])
torch.Size([128, 512])
tensor([[    2, 18510,  7803,  ...,  9680,  3136,     3],
        [    2, 25730,     5,  ...,     0,     0,     0],
        [    2, 23509, 16

In [5]:
!python TripletMarginLossMNIST.py

/home/kaito_sugimoto/metric-learning-tutorial/.venv/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
torch.Size([256, 1, 28, 28])
tensor([[[[-0.4242, -0.4242, -0.4242,  ..., -0.4242, -0.4242, -0.4242],
          [-0.4242, -0.4242, -0.4242,  ..., -0.4242, -0.4242, -0.4242],
          [-0.4242, -0.4242, -0.4242,  ..., -0.4242, -0.4242, -0.4242],
          ...,
          [-0.4242, -0.4242, -0.4242,  ..., -0.4242, -0.4242, -0.4242],
          [-0.4242, -0.4242, -0.424

In [15]:
!python ArcFaceLivedoor.py

torch.Size([128, 128])
tensor([[    2,  1433,  7978,  ...,  1964,     6,     3],
        [    2, 15173, 17734,  ...,   376,   500,     3],
        [    2,    63, 15701,  ..., 25154,  1341,     3],
        ...,
        [    2,  7786,    14,  ...,     5, 21701,     3],
        [    2, 17057,   159,  ...,     6,  1088,     3],
        [    2, 13901,  1993,  ...,     5,  6311,     3]])
torch.Size([128])
tensor([6, 1, 4, 4, 5, 1, 4, 2, 1, 8, 0, 4, 1, 4, 3, 6, 1, 2, 8, 7, 7, 5, 6, 8,
        7, 8, 0, 1, 8, 6, 4, 3, 1, 0, 5, 7, 1, 2, 6, 5, 4, 8, 8, 0, 5, 0, 6, 1,
        2, 6, 3, 8, 5, 2, 3, 7, 4, 7, 2, 4, 4, 8, 7, 7, 0, 3, 0, 5, 7, 1, 1, 4,
        5, 7, 5, 5, 1, 0, 8, 2, 2, 8, 5, 7, 2, 2, 2, 8, 1, 1, 7, 8, 4, 3, 4, 2,
        2, 5, 1, 1, 6, 8, 3, 5, 1, 8, 6, 4, 5, 0, 2, 0, 7, 3, 6, 5, 6, 7, 3, 2,
        6, 3, 7, 0, 4, 0, 4, 1])
torch.Size([128, 128])
tensor([[    2, 18510,  7803,  ..., 21922,    14,     3],
        [    2, 25730,     5,  ...,   308,    10,     3],
        [    2, 23509, 16